//
//  AllRecipesInteractor.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllRecipesBusinessLogic {
	func fetchRecipes(request: AllRecipes.FetchRecipes.Request)
}

protocol AllRecipesDataStore {
	// var name: String { get set }
}

class AllRecipesInteractor: AllRecipesBusinessLogic, AllRecipesDataStore {
	var presenter: AllRecipesPresentationLogic?
	var worker: AllRecipesWorker?
	// var name: String = ""

	// MARK: Fetch The Recipes

	func fetchRecipes(request: AllRecipes.FetchRecipes.Request) {
		worker = AllRecipesWorker()
		worker?.getAllRecipes(completionHandler: { [self] recipes, error in
			let response = AllRecipes.FetchRecipes.Response(recipes: recipes, error: error)
			self.presenter?.presentRecipes(response: response)
		})
	}
}
