//
//  AllRecipesPresenter.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AllRecipesPresentationLogic {
	func presentRecipes(response: AllRecipes.FetchRecipes.Response)
}

class AllRecipesPresenter: AllRecipesPresentationLogic {
	weak var viewController: AllRecipesDisplayLogic?

	// MARK: Present Recipes

	func presentRecipes(response: AllRecipes.FetchRecipes.Response) {
		if let recipes = response.recipes {

			let capitalisedRecipes = recipes.capitalise()

			let viewModel = AllRecipes.FetchRecipes.ViewModel(recipes: capitalisedRecipes)
			viewController?.displayRecipes(viewModel: viewModel)
		}
	}
}
