//
//  AvailableRecipesRouter.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AvailableRecipesRoutingLogic {
	// func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AvailableRecipesDataPassing {
	var dataStore: AvailableRecipesDataStore? { get }
}

class AvailableRecipesRouter: NSObject, AvailableRecipesRoutingLogic, AvailableRecipesDataPassing {
	weak var viewController: AvailableRecipesViewController?
	var dataStore: AvailableRecipesDataStore?

	// MARK: Routing

	// func routeToSomewhere(segue: UIStoryboardSegue?)
	// {
	//  if let segue = segue {
	//    let destinationVC = segue.destination as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//  } else {
	//    let storyboard = UIStoryboard(name: "Main", bundle: nil)
	//    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController")
	//    as! SomewhereViewController
	//    var destinationDS = destinationVC.router!.dataStore!
	//    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
	//    navigateToSomewhere(source: viewController!, destination: destinationVC)
	//  }
	// }

	// MARK: Navigation

	// func navigateToSomewhere(source: AvailableRecipesViewController, destination: SomewhereViewController)
	// {
	//  source.show(destination, sender: nil)
	// }

	// MARK: Passing data

	// func passDataToSomewhere(source: AvailableRecipesDataStore, destination: inout SomewhereDataStore)
	// {
	//  destination.name = source.name
	// }
}
