//
//  AvailableRecipesWorker.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
//  swiftlint:disable vertical_parameter_alignment

import UIKit

class AvailableRecipesWorker {

	func getAllRecipes(completionHandler:@escaping ([Recipe]?, Error?) -> Void) {

		RecipesService.shared.getRecipes { (resp) in
			switch resp {
			case .success(let resp):
				completionHandler(resp, nil)
			case .failure(let err):
				completionHandler(nil, err)
			}
		}
	}

	func getAvailableRecipes(recipes: [Recipe],
							 ingredients: [String],
							 completionHandler:@escaping ([Recipe]?, Error?) -> Void) {

		RecipesService.shared.getRecipes(recipes: recipes, for: ingredients) { (resp) in
			switch resp {
			case .success(let resp):
				completionHandler(resp, nil)
			case .failure(let err):
				completionHandler(nil, err)
			}
		}
	}
}
