//
//  AvailableRecipesPresenter.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AvailableRecipesPresentationLogic {
	func presentAvailableIngredients(response: Ingredients.FetchIngredients.Response)
	func presentRecipes(response: AvailableRecipes.FetchRecipes.Response)
	func presentAvailableRecipes(response: AvailableRecipes.FetchAvailableRecipes.Response)
}

class AvailableRecipesPresenter: AvailableRecipesPresentationLogic {
	weak var viewController: AvailableRecipesDisplayLogic?

	// MARK: Present Recipes

	func presentRecipes(response: AvailableRecipes.FetchRecipes.Response) {
		if let recipes = response.recipes {
			let viewModel = AvailableRecipes.FetchRecipes.ViewModel(recipes: recipes)
			viewController?.returnAllRecipes(viewModel: viewModel)
		}
	}

	func presentAvailableRecipes(response: AvailableRecipes.FetchAvailableRecipes.Response) {
		if let recipes = response.recipes {

			let capitalisedRecipes = recipes.capitalise()

			let viewModel = AvailableRecipes.FetchAvailableRecipes.ViewModel(recipes: capitalisedRecipes)
			viewController?.displayAvailableRecipes(viewModel: viewModel)
		}
	}

	func presentAvailableIngredients(response: Ingredients.FetchIngredients.Response) {

		if let ingredients = response.ingredients {
			let viewModel = Ingredients.FetchIngredients.ViewModel(ingredients: ingredients)
			viewController?.returnAvailableIngredients(viewModel: viewModel)
		}

	}
}
