//
//  IngredientsInteractor.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IngredientsBusinessLogic {
	func fetchIngredients(request: Ingredients.FetchIngredients.Request)
}

protocol IngredientsDataStore {
	// var name: String { get set }
}

class IngredientsInteractor: IngredientsBusinessLogic, IngredientsDataStore {
	var presenter: IngredientsPresentationLogic?
	var worker: IngredientsWorker?
	// var name: String = ""

	func fetchIngredients(request: Ingredients.FetchIngredients.Request) {
		worker = IngredientsWorker()
		worker?.getAvailableIngredients(completionHandler: { ingredients, error in
			let response = Ingredients.FetchIngredients.Response(ingredients: ingredients, error: error)
			self.presenter?.presentAvailableIngredients(response: response)
		})
	}
}
