//
//  IngredientsPresenter.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IngredientsPresentationLogic {

	func presentAvailableIngredients(response: Ingredients.FetchIngredients.Response)
}

class IngredientsPresenter: IngredientsPresentationLogic {
	weak var viewController: IngredientsDisplayLogic?

	// MARK: Present Ingredients

	func presentAvailableIngredients(response: Ingredients.FetchIngredients.Response) {

		if let ingredients = response.ingredients {
			let capitalisedIngredients = ingredients.capitalise() // I prefer capitals
			let viewModel = Ingredients.FetchIngredients.ViewModel(ingredients: capitalisedIngredients)
			viewController?.displayAvailableIngredients(viewModel: viewModel)
		}

	}
}
