//
//  IngredientsModels.swift
//  RecipesInMotion
//
//  Created by Cathal Farrell on 02/09/2021.
//  Copyright (c) 2021 @thal Productions All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
// swiftlint:disable nesting

import UIKit

enum Ingredients {

	enum FetchIngredients {
		struct Request {
		}
		struct Response {
			var ingredients: [String]?
			var error: Error?
		}
		struct ViewModel {
			var ingredients: [String]
			var errorMessage: String?
		}
	}

}
